### ISSUE TITLE
Release 0.3.0 Checklist

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#594]
### Upgrade to Spring Security 5.6+
- [ ] Remove `JoseHeader`, `JoseHeaderNames`, `JwtClaimsSet`, `JwtEncoder`, `JwtEncodingException`, `NimbusJwsEncoder`
- [ ] Remove `OAuth2TokenIntrospectionClaimAccessor`, `OAuth2TokenIntrospectionClaimNames`
- [ ] Remove `OAuth2AccessTokenResponseHttpMessageConverter`
- [ ] `Use OAuth2ErrorCodes.INVALID_REDIRECT_URI`

### Miscellaneous
- [ ] Change `interface` to `final class` - `OidcClientMetadataClaimNames`, `OidcProviderMetadataClaimNames`, `OAuth2AuthorizationServerMetadataClaimNames`
